services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flaskApp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_APP
        value: flaskApp.py